version: '3'
services:
    app:
        build: .
        ports:
            - 8080:8080
        volumes:
            - ./:/code
    nginx:
        image: nginx:1.13
        ports:
            - 80:80
        links:
            - app:app
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf

